name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main  # Set your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Choose the Node version

    - name: Install and Build
      run: |
        npm install
        npm run export
      
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages  # The branch the action should deploy to.
        folder: out       # The folder the action should deploy.
